// Generators for the ClaudeRelay wrapper .app bundle.
//
// PLAN.md section 3 calls for "a stable signed wrapper app, e.g.
// ~/Applications/ClaudeRelay.app, with a fixed bundle id". The signing is a
// later concern; an unsigned bundle still gives TCC a stable
// CFBundleIdentifier that survives Bun upgrades. When the user grants Full
// Disk Access to the wrapper bundle, the grant persists across versioned
// /opt/homebrew/Cellar/bun/* paths.
//
// These functions are pure; the on-disk install (mkdir, write, chmod) lives
// in configure-wrapper.ts and is exercised end-to-end by setup/install.ts.

export const WRAPPER_BUNDLE_ID = "com.claude.telegram-relay-wrapper";
export const WRAPPER_BUNDLE_NAME = "ClaudeRelay";
export const WRAPPER_EXECUTABLE_NAME = "ClaudeRelay";

export interface WrapperInfoPlistOptions {
  version: string;
}

export interface WrapperShellScriptOptions {
  bunRealpath: string;
  projectRoot: string;
  script: string;
  env: Record<string, string>;
  logsDir: string;
}

function shellSingleQuote(value: string): string {
  return `'${value.split("'").join("'\\''")}'`;
}

export function generateWrapperInfoPlist(opts: WrapperInfoPlistOptions): string {
  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">',
    '<plist version="1.0">',
    "<dict>",
    `    <key>CFBundleIdentifier</key>\n    <string>${WRAPPER_BUNDLE_ID}</string>`,
    `    <key>CFBundleName</key>\n    <string>${WRAPPER_BUNDLE_NAME}</string>`,
    `    <key>CFBundleExecutable</key>\n    <string>${WRAPPER_EXECUTABLE_NAME}</string>`,
    "    <key>CFBundlePackageType</key>\n    <string>APPL</string>",
    "    <key>CFBundleInfoDictionaryVersion</key>\n    <string>6.0</string>",
    `    <key>CFBundleShortVersionString</key>\n    <string>${opts.version}</string>`,
    `    <key>CFBundleVersion</key>\n    <string>${opts.version}</string>`,
    "    <key>LSUIElement</key>\n    <true/>",
    "    <key>NSHighResolutionCapable</key>\n    <true/>",
    "</dict>",
    "</plist>",
    "",
  ].join("\n");
}

export function generateWrapperShellScript(opts: WrapperShellScriptOptions): string {
  const exports = Object.entries(opts.env)
    .map(([key, value]) => `export ${key}=${shellSingleQuote(value)}`)
    .join("\n");
  return [
    "#!/bin/bash",
    "# Generated by setup/configure-wrapper.ts. Do not edit by hand; rerun the",
    "# setup command and the bundle will be regenerated with current paths.",
    "set -euo pipefail",
    exports,
    `cd ${shellSingleQuote(opts.projectRoot)}`,
    `mkdir -p ${shellSingleQuote(opts.logsDir)}`,
    `exec ${shellSingleQuote(opts.bunRealpath)} run ${shellSingleQuote(opts.script)}`,
    "",
  ].join("\n");
}
